# Generated by Django 3.0.7 on 2020-06-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200614_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Title',
            new_name='title',
        ),
    ]
