# Generated by Django 3.0.7 on 2020-06-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200628_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.CharField(max_length=100),
        ),
    ]
