# Generated by Django 3.0.7 on 2020-06-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='education_date',
            new_name='graduation_date',
        ),
    ]
