# Generated by Django 3.0.7 on 2020-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200621_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_location',
            field=models.CharField(max_length=100),
        ),
    ]
