# Generated by Django 3.0.7 on 2020-06-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200621_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_date',
            new_name='project_date_location',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_date',
            new_name='work_date_location',
        ),
    ]
